name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: pull_request
        uses: actions/checkout@v4

      - name: setting up python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: req.txt is being read
        run: pip install -r requirements.txt

      - name: running the tests...
        run: pytest

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: pull_request
        uses: actions/checkout@v4

      - name: building the docker image
        run: docker build -t pipeline-project .